server:
  port: 8010
spring:
  application:
    name: discoveryService
eureka:
  client:
      register-with-eureka: false
      fetch-registry: false
      preferIpAddress: true
      serviceUrl:
        defaultZone: http://localhost:8010/eureka
